### ISSUE TITLE
求ai绘图api

### ISSUE THREAD

**Issue by WhyPilotXia** [MeetWq/mybot#11]
仔细看了代码发现最终指向.env.dev但并未提供网址

**Comment by MeetWq** [comment]
我当初是自建的哦，而且我已经很久没玩过了，建议去别处找

**Comment by WhyPilotXia** [comment]
好的，收到，谢谢



---Original---
From: ***@***.***&gt;
Sent at: 2024年2月7日(Wed) PM2:14
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MeetWq/mybot] 求ai绘图api (Issue #11)




 
我当初是自建的哦，而且我已经很久没玩过了，建议去别处找
