### ISSUE TITLE
建议把fonts文件单独分离出来放在data文件夹下面

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/mybot#7]
RT，font文件很大，如果每个插件都配在单独一个插件文件夹下面会比较浪费空间（然而好像也浪费不了多少？）
指的是petpet和memes这些需要字体的插件

**Comment by MeetWq** [comment]
之前就是这么做的，但拆分成单独的插件后就变成现在这样了
不知道有没有更好的方案
